/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/* Loop forever */
	/*
	MGPIO_vSetPullType(_GPIOA_PORT, GPIO_PIN_5, _PULL_OFF);
	MGPIO_vSetPinMode(_GPIOA_PORT, GPIO_PIN_5, _MODE_OUTPUT);
	MGPIO_vSetPinOutPutType(_GPIOA_PORT, GPIO_PIN_5, _OUTPUT_TYPE_PUSH_PULL);
	MGPIO_vSetPinOutSpeed(_GPIOA_PORT, GPIO_PIN_5, _OUTPUT_SPEED_MEDUIM);*/
	//LCD_enuInit();
#include <stdint.h>
#include "STD_TYPES.h"
#include "RCC_interface.h"
#include "Delay_interface.h"
#include "GPIO_interface.h"

#include "BIT_MATH.h"

#include "SPI_interface.h"
#include "GARAGE_DISPLAY_Interface.h"


int main(void)
{

	MRCC_vInitSystemCLK();
	MRCC_vEnableClock(AHB1,_PERIPHERAL_EN_GPIOA);
	MRCC_vEnableClock(AHB1,_PERIPHERAL_EN_GPIOD);
	MRCC_vEnableClock(APB2, _PERIPHERAL_EN_SPI1);
	MGPIO_vSetPinMode(_GPIOD_PORT,GPIO_PIN_11,_MODE_OUTPUT);
	//SPI_vInit();
	GARAGE_DISPLAY_void_Init();
	//u16 col=0X4589;
	//HTFT_void_DisplayLine(7, 10, 105, 100,&col,2);
	//col=0XFB00;
	//HTFT_void_DisplayHorizontalLine(7, 10, 105, 10,&col,2);
	//col=0X00FB;
	//HTFT_void_DisplayLine(105, 10, 105, 100,&col,2);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_1,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_2,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_3,Location_BUSY);
	Delay_vMsIn16MHz(500);

	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_4,Location_BUSY);
	Delay_vMsIn16MHz(500);

	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_5,Location_BUSY);
	Delay_vMsIn16MHz(500);

	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_6,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_3,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_2,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_4,Location_EMPTY);
	Delay_vMsIn16MHz(500);

	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_5,Location_EMPTY);
	Delay_vMsIn16MHz(500);

	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_6,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Car_1,Location_EMPTY);
	//HTFT_void_DisplayLine(Copy_u16_X1, Copy_u16_Y1, Copy_u16_X2, Copy_u16_Y2));
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_1,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_2,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_2,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_3,Location_BUSY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_4,Location_BUSY);

	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_1,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_2,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_2,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_3,Location_EMPTY);
	Delay_vMsIn16MHz(500);
	GARAGE_DISPLAY_void_PositionDisplay(Location_Bike_4,Location_EMPTY);



	while(1)
	{
		MGPIO_vWriteDataDIR(_GPIOD_PORT,GPIO_PIN_11,_HIGH);
		Delay_vMsIn16MHz(1000);
		MGPIO_vWriteData(_GPIOD_PORT,GPIO_PIN_11,_LOW);
		Delay_vMsIn16MHz(1000);
		//SPI_u8SendRecive(SPI1,5);
		//Delay_vMsIn16MHz(1000);
		//SPI_u8SendRecive(SPI1,7);
		//Delay_vMsIn16MHz(1000);
		//SPI_u8SendRecive(SPI1,20);
		//Delay_vMsIn16MHz(1000);
		//SPI_u8SendRecive(SPI1,30);
		//Delay_vMsIn16MHz(1000);

	}
}
