/*
 * LMATRIX_config.h
 *
 *  Created on: Nov 25, 2022
 *      Author: abano
 */

#ifndef HALL_LMARIX_LMATRIX_CONFIG_H_
#define HALL_LMARIX_LMATRIX_CONFIG_H_

#define ROW_NUM				32
#define COL_NUM				8

#define ROW_GROUPS	{_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT\
					,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOA_PORT,_GPIOD_PORT,_GPIOA_PORT,_GPIOA_PORT\
					,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,\
					_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,_GPIOC_PORT,}

#define ROW_PINS	{GPIO_PIN_0,GPIO_PIN_1,GPIO_PIN_2,GPIO_PIN_3,GPIO_PIN_4,GPIO_PIN_5,GPIO_PIN_6,GPIO_PIN_7\
					,GPIO_PIN_8,GPIO_PIN_9,GPIO_PIN_10,GPIO_PIN_11,GPIO_PIN_12,GPIO_PIN_13,GPIO_PIN_14,GPIO_PIN_15,\
					GPIO_PIN_0,GPIO_PIN_1,GPIO_PIN_2,GPIO_PIN_3,GPIO_PIN_4,GPIO_PIN_5,GPIO_PIN_6,GPIO_PIN_7\
					,GPIO_PIN_8,GPIO_PIN_9,GPIO_PIN_10,GPIO_PIN_11,GPIO_PIN_12,GPIO_PIN_13,GPIO_PIN_14,GPIO_PIN_15}



#define COL_GROUPS	{_GPIOD_PORT,_GPIOD_PORT,_GPIOD_PORT,_GPIOD_PORT,_GPIOD_PORT,_GPIOD_PORT,_GPIOD_PORT,_GPIOD_PORT}

#define COL_PINS  	{GPIO_PIN_0,GPIO_PIN_1,GPIO_PIN_2,GPIO_PIN_3,GPIO_PIN_4,GPIO_PIN_5,GPIO_PIN_6,GPIO_PIN_7}



#endif /* HALL_LMARIX_LMATRIX_CONFIG_H_ */
