 /******************************************************************
    // SPI.c
    - Created: /5/2022
    - Author: Magdy
    - Version : V01
  *****************************************************************/

#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "SPI_interface.h"
#include "SPI_private.h"
#include "SPI_config.h"


void SPI_vInit(void)
{
	#if SPI1_ENABLED  == ENABLED


	SPI1->CR1.BIT.BIDIMODE = SPI1_BIDIMODE_MODE;
	SPI1->CR1.BIT.BIDIOE   = SPI1_BIDIOE_MODE  ;
	SPI1->CR1.BIT.CRCEN    = SPI1_CRC_EN       ;
	SPI1->CR1.BIT.CRCNEXT  = SPI1_CRC_NEXT     ;
	SPI1->CR1.BIT.DFF      = SPI1_DATA_FRAME   ;
	SPI1->CR1.BIT.RXONLY   = SPI1_RX_ONLY      ;
	SPI1->CR1.BIT.SSM      = SPI1_SSM_MODE     ;
	SPI1->CR1.BIT.SSI      = SPI1_SSI_MODE     ;
	SPI1->CR1.BIT.LSBFIRST = SPI1_LSB_FIRST    ;
	SPI1->CR1.BIT.BR       = SPI1_BR_CONTROL   ;
	SPI1->CR1.BIT.MSTR     = SPI1_MSTR_SELECT  ;
	SPI1->CR1.BIT.CPOL     = SPI1_CPOL_CONTROL ;
	SPI1->CR1.BIT.CPHA     = SPI1_CPHA_CONTROL ;
	SPI1->CR1.BIT.SPE      = SPI_ENABLE        ;
	//SPI1->CR1.RES = Local_CR1.RES;
	#elif SPI1_ENABLED  == DISABLED
	//   SPI1->CR1.SPE= SPI_DISABLE   ;
	#endif
	
	#if SPI2_ENABLED  == ENABLED
	SPI2->CR1.BIT.BIDIMODE = SPI2_BIDIMODE_MODE;
	SPI2->CR1.BIT.BIDIOE   = SPI2_BIDIOE_MODE  ;
	SPI2->CR1.BIT.CRCEN    = SPI2_CRC_EN       ;
	SPI2->CR1.BIT.CRCNEXT  = SPI2_CRC_NEXT     ;
	SPI2->CR1.BIT.DFF      = SPI2_DATA_FRAME   ;
	SPI2->CR1.BIT.RXONLY   = SPI2_RX_ONLY      ;
	SPI2->CR1.BIT.SSM      = SPI2_SSM_MODE     ;
	SPI2->CR1.BIT.SSI      = SPI2_SSI_MODE     ;
	SPI2->CR1.BIT.LSBFIRST = SPI2_LSB_FIRST    ;
	SPI2->CR1.BIT.BR       = SPI2_BR_CONTROL   ;
	SPI2->CR1.BIT.MSTR     = SPI2_MSTR_SELECT  ;
	SPI2->CR1.BIT.CPOL     = SPI2_CPOL_CONTROL ;
	SPI2->CR1.BIT.CPHA     = SPI2_CPHA_CONTROL ;
	SPI2->CR1.BIT.SPE      = SPI2_SPI_E        ;
	#elif  SPI2_ENABLED  == DISABLED
   //    SPI2->CR1.SPE= SPI_DISABLE   ;
	#endif
	
	#if SPI3_ENABLED  == ENABLED
		SPI3->CR1.BIT.BIDIMODE = SPI3_BIDIMODE_MODE;
		SPI3->CR1.BIT.BIDIOE   = SPI3_BIDIOE_MODE  ;
		SPI3->CR1.BIT.CRCEN    = SPI3_CRC_EN       ;
		SPI3->CR1.BIT.CRCNEXT  = SPI3_CRC_NEXT     ;
		SPI3->CR1.BIT.DFF      = SPI3_DATA_FRAME   ;
		SPI3->CR1.BIT.RXONLY   = SPI3_RX_ONLY      ;
		SPI3->CR1.BIT.SSM      = SPI3_SSM_MODE     ;
		SPI3->CR1.BIT.SSI      = SPI3_SSI_MODE     ;
		SPI3->CR1.BIT.LSBFIRST = SPI3_LSB_FIRST    ;
		SPI3->CR1.BIT.BR       = SPI3_BR_CONTROL   ;
		SPI3->CR1.BIT.MSTR     = SPI3_MSTR_SELECT  ;
		SPI3->CR1.BIT.CPOL     = SPI3_CPOL_CONTROL ;
		SPI3->CR1.BIT.CPHA     = SPI3_CPHA_CONTROL ;
		SPI3->CR1.BIT.SPE      = SPI3_SPI_E        ;

	#elif  SPI3_ENABLED  == DISABLED
            //SPI3->CR1.BIT.SPE= SPI_DISABLE   ;
	#endif
	
	#if SPI4_ENABLED  == ENABLED
	SPI4->CR1.BIT.BIDIMODE = SPI4_BIDIMODE_MODE;
	SPI4->CR1.BIT.BIDIOE   = SPI4_BIDIOE_MODE  ;
	SPI4->CR1.BIT.CRCEN    = SPI4_CRC_EN       ;
	SPI4->CR1.BIT.CRCNEXT  = SPI4_CRC_NEXT     ;
	SPI4->CR1.BIT.DFF      = SPI4_DATA_FRAME   ;
	SPI4->CR1.BIT.RXONLY   = SPI4_RX_ONLY      ;
	SPI4->CR1.BIT.SSM      = SPI4_SSM_MODE     ;
	SPI4->CR1.BIT.SSI      = SPI4_SSI_MODE     ;
	SPI4->CR1.BIT.LSBFIRST = SPI4_LSB_FIRST    ;
	SPI4->CR1.BIT.BR       = SPI4_BR_CONTROL   ;
	SPI4->CR1.BIT.MSTR     = SPI4_MSTR_SELECT  ;
	SPI4->CR1.BIT.CPOL     = SPI4_CPOL_CONTROL ;
	SPI4->CR1.BIT.CPHA     = SPI4_CPHA_CONTROL ;
	SPI4->CR1.BIT.SPE      = SPI4_SPI_E        ;
	#elif  SPI4_ENABLED  == DISABLED
	  //  SPI4->CR1.SPE= SPI_DISABLE   ;
	#endif
	//SPI1->CR1.RES = 0X347;

}
u8 SPI_u8SendRecive(SPI_t* SPI_ptrIndex,u8 Copy_u8Data)
{
	 SPI_t* ptr=0;
	 ptr = SPI_ptrIndex;
	 u8 Local_u8Recive=0;
     ptr->DR=Copy_u8Data;
     while ((GET_BIT(ptr->SR,BSY))==1);
     Local_u8Recive=(u8)ptr->DR;

     return Local_u8Recive;



}
